import type { Metadata } from "next";
import { poppins } from "@/app/fonts";
import "./globals.css";
import UserNavBar from "@/app/components/UserNavBar";
import AuthProvider from "@/provider/authProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-white`} >
        <AuthProvider>
          <UserNavBar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}